# Generated by Django 5.1.7 on 2025-03-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='current_cycle_used',
            new_name='distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_location',
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driving_hours', models.FloatField()),
                ('rest_hours', models.FloatField()),
                ('fuel_stops', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip')),
            ],
        ),
    ]
